export const CAR_CREATE_REQUEST = 'CAR_CREATE_REQUEST'
export const CAR_CREATE_SUCCESS = 'CAR_CREATE_SUCCESS'
export const CAR_CREATE_FAILED = 'CAR_CREATE_FAILED'
export const CAR_CREATE_RESET = 'CAR_CREATE_RESET'

export const CAR_GET_ALL_REQUEST = 'CAR_GET_ALL_REQUEST'
export const CAR_GET_ALL_SUCCESS = 'CAR_GET_ALL_SUCCESS'
export const CAR_GET_ALL_FAILED = 'CAR_GET_ALL_FAILED'

export const CAR_GET_ONE_REQUEST = 'CAR_GET_ONE_REQUEST'
export const CAR_GET_ONE_SUCCESS = 'CAR_GET_ONE_SUCCESS'
export const CAR_GET_ONE_FAILED = 'CAR_GET_ONE_FAILED'

export const CAR_UPDATE_REQUEST = 'CAR_UPDATE_REQUEST'
export const CAR_UPDATE_SUCCESS = 'CAR_UPDATE_SUCCESS'
export const CAR_UPDATE_FAILED = 'CAR_UPDATE_FAILED'
export const CAR_UPDATE_RESET = 'CAR_UPDATE_RESET'

export const CAR_REMOVE_REQUEST = 'CAR_REMOVE_REQUEST'
export const CAR_REMOVE_SUCCESS = 'CAR_REMOVE_SUCCESS'
export const CAR_REMOVE_FAILED = 'CAR_REMOVE_FAILED'
export const CAR_REMOVE_RESET = 'CAR_REMOVE_RESET'

export const CAR_GET_CONNECTION_REQUEST = 'CAR_GET_CONNECTION_REQUEST'
export const CAR_GET_CONNECTION_SUCCESS = 'CAR_GET_CONNECTION_SUCCESS'
export const CAR_GET_CONNECTION_ERROR = 'CAR_GET_CONNECTION_ERROR'
export const CAR_GET_CONNECTION_RESET = 'CAR_GET_CONNECTION_RESET'

export const CAR_ALLOWED_TYPES = ["passengerCar", "engineCar", "bikeCar"]