export const ROUTE_CREATE_REQUEST = 'ROUTE_CREATE_REQUEST'
export const ROUTE_CREATE_SUCCESS = 'ROUTE_CREATE_SUCCESS'
export const ROUTE_CREATE_FAILED = 'ROUTE_CREATE_FAILED'
export const ROUTE_CREATE_RESET = 'ROUTE_CREATE_RESET'

export const ROUTE_GET_ALL_REQUEST = 'ROUTE_GET_ALL_REQUEST'
export const ROUTE_GET_ALL_SUCCESS = 'ROUTE_GET_ALL_SUCCESS'
export const ROUTE_GET_ALL_FAILED = 'ROUTE_GET_ALL_FAILED'

export const ROUTE_GET_ONE_REQUEST = 'ROUTE_GET_ONE_REQUEST'
export const ROUTE_GET_ONE_SUCCESS = 'ROUTE_GET_ONE_SUCCESS'
export const ROUTE_GET_ONE_FAILED = 'ROUTE_GET_ONE_FAILED'

export const ROUTE_UPDATE_REQUEST = 'ROUTE_UPDATE_REQUEST'
export const ROUTE_UPDATE_SUCCESS = 'ROUTE_UPDATE_SUCCESS'
export const ROUTE_UPDATE_FAILED = 'ROUTE_UPDATE_FAILED'
export const ROUTE_UPDATE_RESET = 'ROUTE_UPDATE_RESET'

export const ROUTE_REMOVE_REQUEST = 'ROUTE_REMOVE_REQUEST'
export const ROUTE_REMOVE_SUCCESS = 'ROUTE_REMOVE_SUCCESS'
export const ROUTE_REMOVE_FAILED = 'ROUTE_REMOVE_FAILED'
export const ROUTE_REMOVE_RESET = 'ROUTE_REMOVE_RESET'

export const ROUTE_GET_CONNECTION_REQUEST = 'ROUTE_GET_CONNECTION_REQUEST'
export const ROUTE_GET_CONNECTION_SUCCESS = 'ROUTE_GET_CONNECTION_SUCCESS'
export const ROUTE_GET_CONNECTION_ERROR = 'ROUTE_GET_CONNECTION_ERROR'
export const ROUTE_GET_CONNECTION_RESET = 'ROUTE_GET_CONNECTION_RESET'