export const RUN_CREATE_REQUEST = 'RUN_CREATE_REQUEST'
export const RUN_CREATE_SUCCESS = 'RUN_CREATE_SUCCESS'
export const RUN_CREATE_FAILED = 'RUN_CREATE_FAILED'
export const RUN_CREATE_RESET = 'RUN_CREATE_RESET'

export const RUN_GET_ALL_REQUEST = 'RUN_GET_ALL_REQUEST'
export const RUN_GET_ALL_SUCCESS = 'RUN_GET_ALL_SUCCESS'
export const RUN_GET_ALL_FAILED = 'RUN_GET_ALL_FAILED'

export const RUN_GET_ONE_REQUEST = 'RUN_GET_ONE_REQUEST'
export const RUN_GET_ONE_SUCCESS = 'RUN_GET_ONE_SUCCESS'
export const RUN_GET_ONE_FAILED = 'RUN_GET_ONE_FAILED'

export const RUN_UPDATE_REQUEST = 'RUN_UPDATE_REQUEST'
export const RUN_UPDATE_SUCCESS = 'RUN_UPDATE_SUCCESS'
export const RUN_UPDATE_FAILED = 'RUN_UPDATE_FAILED'
export const RUN_UPDATE_RESET = 'RUN_UPDATE_RESET'

export const RUN_REMOVE_REQUEST = 'RUN_REMOVE_REQUEST'
export const RUN_REMOVE_SUCCESS = 'RUN_REMOVE_SUCCESS'
export const RUN_REMOVE_FAILED = 'RUN_REMOVE_FAILED'
export const RUN_REMOVE_RESET = 'RUN_REMOVE_RESET'

export const RUN_GET_CONNECTION_REQUEST = 'RUN_GET_CONNECTION_REQUEST'
export const RUN_GET_CONNECTION_SUCCESS = 'RUN_GET_CONNECTION_SUCCESS'
export const RUN_GET_CONNECTION_FAILED = 'RUN_GET_CONNECTION_FAILED'
export const RUN_GET_CONNECTION_RESET = 'RUN_GET_CONNECTION_RESET'
