export const SEAT_CREATE_REQUEST = 'SEAT_CREATE_REQUEST'
export const SEAT_CREATE_SUCCESS = 'SEAT_CREATE_SUCCESS'
export const SEAT_CREATE_FAILED = 'SEAT_CREATE_FAILED'
export const SEAT_CREATE_RESET = 'SEAT_CREATE_RESET'

export const SEAT_GET_ALL_REQUEST = 'SEAT_GET_ALL_REQUEST'
export const SEAT_GET_ALL_SUCCESS = 'SEAT_GET_ALL_SUCCESS'
export const SEAT_GET_ALL_FAILED = 'SEAT_GET_ALL_FAILED'

export const SEAT_GET_ONE_REQUEST = 'SEAT_GET_ONE_REQUEST'
export const SEAT_GET_ONE_SUCCESS = 'SEAT_GET_ONE_SUCCESS'
export const SEAT_GET_ONE_FAILED = 'SEAT_GET_ONE_FAILED'

export const SEAT_UPDATE_REQUEST = 'SEAT_UPDATE_REQUEST'
export const SEAT_UPDATE_SUCCESS = 'SEAT_UPDATE_SUCCESS'
export const SEAT_UPDATE_FAILED = 'SEAT_UPDATE_FAILED'
export const SEAT_UPDATE_RESET = 'SEAT_UPDATE_RESET'

export const SEAT_REMOVE_REQUEST = 'SEAT_REMOVE_REQUEST'
export const SEAT_REMOVE_SUCCESS = 'SEAT_REMOVE_SUCCESS'
export const SEAT_REMOVE_FAILED = 'SEAT_REMOVE_FAILED'
export const SEAT_REMOVE_RESET = 'SEAT_REMOVE_RESET'

export const SEAT_GET_CONNECTION_REQUEST = 'SEAT_GET_CONNECTION_REQUEST'
export const SEAT_GET_CONNECTION_SUCCESS = 'SEAT_GET_CONNECTION_SUCCESS'
export const SEAT_GET_CONNECTION_ERROR = 'SEAT_GET_CONNECTION_ERROR'
export const SEAT_GET_CONNECTION_RESET = 'SEAT_GET_CONNECTION_RESET'

export const SEAT_GET_TAKEN_REQUEST = 'SEAT_GET_TAKEN_REQUEST'
export const SEAT_GET_TAKEN_SUCCESS = 'SEAT_GET_TAKEN_SUCCESS'
export const SEAT_GET_TAKEN_ERROR = 'SEAT_GET_TAKEN_ERROR'
export const SEAT_GET_TAKEN_RESET = 'SEAT_GET_TAKEN_RESET'
