export const STATION_CREATE_REQUEST = 'STATION_CREATE_REQUEST'
export const STATION_CREATE_SUCCESS = 'STATION_CREATE_SUCCESS'
export const STATION_CREATE_FAILED = 'STATION_CREATE_FAILED'
export const STATION_CREATE_RESET = 'STATION_CREATE_RESET'

export const STATION_GET_ALL_REQUEST = 'STATION_GET_ALL_REQUEST'
export const STATION_GET_ALL_SUCCESS = 'STATION_GET_ALL_SUCCESS'
export const STATION_GET_ALL_FAILED = 'STATION_GET_ALL_FAILED'

export const STATION_GET_ONE_REQUEST = 'STATION_GET_ONE_REQUEST'
export const STATION_GET_ONE_SUCCESS = 'STATION_GET_ONE_SUCCESS'
export const STATION_GET_ONE_FAILED = 'STATION_GET_ONE_FAILED'

export const STATION_GET_ALL_CONN_REQUEST = 'STATION_GET_ALL_CONN_REQUEST'
export const STATION_GET_ALL_CONN_SUCCESS = 'STATION_GET_ALL_CONN_SUCCESS'
export const STATION_GET_ALL_CONN_FAILED = 'STATION_GET_ALL_CONN_FAILED'

export const STATION_UPDATE_REQUEST = 'STATION_UPDATE_REQUEST'
export const STATION_UPDATE_SUCCESS = 'STATION_UPDATE_SUCCESS'
export const STATION_UPDATE_FAILED = 'STATION_UPDATE_FAILED'
export const STATION_UPDATE_RESET = 'STATION_UPDATE_RESET'

export const STATION_REMOVE_REQUEST = 'STATION_REMOVE_REQUEST'
export const STATION_REMOVE_SUCCESS = 'STATION_REMOVE_SUCCESS'
export const STATION_REMOVE_FAILED = 'STATION_REMOVE_FAILED'
export const STATION_REMOVE_RESET = 'STATION_REMOVE_RESET'