export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST'
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS'
export const TICKET_CREATE_FAILED = 'TICKET_CREATE_FAILED'
export const TICKET_CREATE_RESET = 'TICKET_CREATE_RESET'

export const TICKET_VALIDATE_REQUEST = 'TICKET_VALIDATE_REQUEST'
export const TICKET_VALIDATE_SUCCESS = 'TICKET_VALIDATE_SUCCESS'
export const TICKET_VALIDATE_FAILED = 'TICKET_VALIDATE_FAILED'
export const TICKET_VALIDATE_RESET = 'TICKET_VALIDATE_RESET'

export const TICKET_GET_ALL_REQUEST = 'TICKET_GET_ALL_REQUEST'
export const TICKET_GET_ALL_SUCCESS = 'TICKET_GET_ALL_SUCCESS'
export const TICKET_GET_ALL_FAILED = 'TICKET_GET_ALL_FAILED'

export const TICKET_GET_ONE_REQUEST = 'TICKET_GET_ONE_REQUEST'
export const TICKET_GET_ONE_SUCCESS = 'TICKET_GET_ONE_SUCCESS'
export const TICKET_GET_ONE_FAILED = 'TICKET_GET_ONE_FAILED'

export const TICKET_UPDATE_REQUEST = 'TICKET_UPDATE_REQUEST'
export const TICKET_UPDATE_SUCCESS = 'TICKET_UPDATE_SUCCESS'
export const TICKET_UPDATE_FAILED = 'TICKET_UPDATE_FAILED'
export const TICKET_UPDATE_RESET = 'TICKET_UPDATE_RESET'

export const TICKET_REMOVE_REQUEST = 'TICKET_REMOVE_REQUEST'
export const TICKET_REMOVE_SUCCESS = 'TICKET_REMOVE_SUCCESS'
export const TICKET_REMOVE_FAILED = 'TICKET_REMOVE_FAILED'
export const TICKET_REMOVE_RESET = 'TICKET_REMOVE_RESET'