export const TRAIN_CREATE_REQUEST = 'TRAIN_CREATE_REQUEST'
export const TRAIN_CREATE_SUCCESS = 'TRAIN_CREATE_SUCCESS'
export const TRAIN_CREATE_FAILED = 'TRAIN_CREATE_FAILED'
export const TRAIN_CREATE_RESET = 'TRAIN_CREATE_RESET'

export const TRAIN_GET_ALL_REQUEST = 'TRAIN_GET_ALL_REQUEST'
export const TRAIN_GET_ALL_SUCCESS = 'TRAIN_GET_ALL_SUCCESS'
export const TRAIN_GET_ALL_FAILED = 'TRAIN_GET_ALL_FAILED'

export const TRAIN_GET_ONE_REQUEST = 'TRAIN_GET_ONE_REQUEST'
export const TRAIN_GET_ONE_SUCCESS = 'TRAIN_GET_ONE_SUCCESS'
export const TRAIN_GET_ONE_FAILED = 'TRAIN_GET_ONE_FAILED'

export const TRAIN_UPDATE_REQUEST = 'TRAIN_UPDATE_REQUEST'
export const TRAIN_UPDATE_SUCCESS = 'TRAIN_UPDATE_SUCCESS'
export const TRAIN_UPDATE_FAILED = 'TRAIN_UPDATE_FAILED'
export const TRAIN_UPDATE_RESET = 'TRAIN_UPDATE_RESET'

export const TRAIN_REMOVE_REQUEST = 'TRAIN_REMOVE_REQUEST'
export const TRAIN_REMOVE_SUCCESS = 'TRAIN_REMOVE_SUCCESS'
export const TRAIN_REMOVE_FAILED = 'TRAIN_REMOVE_FAILED'
export const TRAIN_REMOVE_RESET = 'TRAIN_REMOVE_RESET'

export const TRAIN_GET_CONNECTION_REQUEST = 'TRAIN_GET_CONNECTION_REQUEST'
export const TRAIN_GET_CONNECTION_SUCCESS = 'TRAIN_GET_CONNECTION_SUCCESS'
export const TRAIN_GET_CONNECTION_ERROR = 'TRAIN_GET_CONNECTION_ERROR'
export const TRAIN_GET_CONNECTION_RESET = 'TRAIN_GET_CONNECTION_RESET'

export const TRAIN_CONTROL_CREATE_REQUEST = 'TRAIN_CONTROL_CREATE_REQUEST'
export const TRAIN_CONTROL_CREATE_SUCCESS = 'TRAIN_CONTROL_CREATE_SUCCESS'
export const TRAIN_CONTROL_CREATE_FAILED = 'TRAIN_CONTROL_CREATE_FAILED'

export const TRAIN_CONTROL_GET_ALL_REQUEST = 'TRAIN_CONTROL_GET_ALL_REQUEST'
export const TRAIN_CONTROL_GET_ALL_SUCCESS = 'TRAIN_CONTROL_GET_ALL_SUCCESS'
export const TRAIN_CONTROL_GET_ALL_FAILED = 'TRAIN_CONTROL_GET_ALL_FAILED'

export const TRAIN_CONTROL_REMOVE_REQUEST = 'TRAIN_CONTROL_REMOVE_REQUEST'
export const TRAIN_CONTROL_REMOVE_SUCCESS = 'TRAIN_CONTROL_REMOVE_SUCCESS'
export const TRAIN_CONTROL_REMOVE_FAILED = 'TRAIN_CONTROL_REMOVE_FAILED'

export const TRAIN_CONTROL_UPDATE_REQUEST = 'TRAIN_CONTROL_UPDATE_REQUEST'
export const TRAIN_CONTROL_UPDATE_SUCCESS = 'TRAIN_CONTROL_UPDATE_SUCCESS'
export const TRAIN_CONTROL_UPDATE_FAILED = 'TRAIN_CONTROL_UPDATE_FAILED'
